#!/usr/bin/env bash
# Install LingBot-Map on Thumper (or any CUDA Linux host).
#
# Hardware notes (thumper.local as of 2026-07):
#   - NVIDIA TITAN Xp 12 GB, driver 535 → max CUDA 12.2
#   - Official README wants torch 2.8 + cu128; that needs a newer driver.
#   - This installer uses torch cu121 + SDPA fallback (FlashInfer optional).
#
# Layout (defaults):
#   SRC     = ~/Documents/DragonSDR/Robbyant/lingbot-map   (git clone)
#   PREFIX  = ~/Data/lingbot-map                           (venv, models, outputs)
#
# Usage:
#   ./tools/lingbot-map/install.sh
#   LINGBOT_MAP_PREFIX=~/Data/lingbot-map ./tools/lingbot-map/install.sh --download-model long
set -euo pipefail

SRC="${LINGBOT_MAP_SRC:-$HOME/Documents/DragonSDR/Robbyant/lingbot-map}"
PREFIX="${LINGBOT_MAP_PREFIX:-$HOME/Data/lingbot-map}"
REPO_URL="${LINGBOT_MAP_REPO:-https://github.com/Robbyant/lingbot-map.git}"
PYTHON="${LINGBOT_MAP_PYTHON:-python3.10}"
TORCH_INDEX="${LINGBOT_MAP_TORCH_INDEX:-https://download.pytorch.org/whl/cu121}"
# Pin compatible with driver 530+ / CUDA 12.1 wheels (TITAN Xp on driver 535).
TORCH_VER="${LINGBOT_MAP_TORCH_VER:-2.5.1}"
TV_VER="${LINGBOT_MAP_TORCHVISION_VER:-0.20.1}"

DOWNLOAD_MODEL=""
WITH_FLASHINFER=0
WITH_RENDER=0

usage() {
  cat <<'EOF'
Usage: install.sh [options]

  --download-model {long|balanced|stage1|all}
      Download checkpoint(s) from Hugging Face into $PREFIX/models/
  --with-flashinfer
      Try installing flashinfer-python (may fail on older GPUs; optional)
  --with-render
      Install offline render extras (open3d, etc.) — heavy
  -h, --help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --download-model) DOWNLOAD_MODEL="${2:-}"; shift 2 ;;
    --with-flashinfer) WITH_FLASHINFER=1; shift ;;
    --with-render) WITH_RENDER=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; usage; exit 1 ;;
  esac
done

mkdir -p "$PREFIX"/{models,outputs,logs,inputs} "$(dirname "$SRC")"

if [[ ! -d "$SRC/.git" ]]; then
  echo "==> Cloning $REPO_URL → $SRC"
  git clone --depth 1 "$REPO_URL" "$SRC"
else
  echo "==> Updating existing clone at $SRC"
  git -C "$SRC" fetch --depth 1 origin
  git -C "$SRC" reset --hard origin/main
fi

VENV="$PREFIX/venv"
if [[ ! -x "$VENV/bin/python" ]]; then
  echo "==> Creating Python 3.10 env at $VENV"
  if "$PYTHON" -m venv "$VENV" 2>/tmp/lingbot-venv.err; then
    :
  elif [[ -x "$HOME/anaconda3/bin/conda" ]]; then
    echo "    system venv unavailable; using conda python=3.10"
    # shellcheck disable=SC1091
    source "$HOME/anaconda3/etc/profile.d/conda.sh"
    conda create -y -p "$VENV" python=3.10
  else
    cat /tmp/lingbot-venv.err >&2 || true
    echo "ERROR: need python3-venv or conda to create $VENV" >&2
    exit 1
  fi
fi
# Prefer direct binaries — conda prefix envs often lack bin/activate
PY="$VENV/bin/python"
PIP="$VENV/bin/pip"
if [[ ! -x "$PY" ]]; then
  echo "ERROR: no python at $PY" >&2
  exit 1
fi

"$PY" -m pip install -U pip setuptools wheel

echo "==> Installing PyTorch $TORCH_VER (cu121 index)"
"$PIP" install "torch==${TORCH_VER}" "torchvision==${TV_VER}" --index-url "$TORCH_INDEX"

echo "==> Installing lingbot-map (editable + vis extras)"
"$PIP" install -e "${SRC}[vis]"

if [[ "$WITH_FLASHINFER" -eq 1 ]]; then
  echo "==> Installing flashinfer-python (optional)"
  "$PIP" install --index-url https://pypi.org/simple flashinfer-python || \
    echo "WARN: flashinfer install failed — demo will use --use_sdpa" >&2
fi

if [[ "$WITH_RENDER" -eq 1 ]]; then
  echo "==> Installing render extras"
  "$PIP" install -e "${SRC}[vis,render]" || \
    echo "WARN: render extras failed" >&2
fi

download_one() {
  local name="$1"
  local dest="$PREFIX/models/${name}.pt"
  if [[ -f "$dest" ]]; then
    echo "    already present: $dest"
    return 0
  fi
  echo "    downloading $name → $dest"
  "$PY" - <<PY
from huggingface_hub import hf_hub_download
import shutil, os
path = hf_hub_download(repo_id="robbyant/lingbot-map", filename="${name}.pt")
shutil.copy2(path, "${dest}")
print("saved", "${dest}", "bytes", os.path.getsize("${dest}"))
PY
}

if [[ -n "$DOWNLOAD_MODEL" ]]; then
  echo "==> Downloading model checkpoint(s): $DOWNLOAD_MODEL"
  case "$DOWNLOAD_MODEL" in
    long) download_one lingbot-map-long ;;
    balanced) download_one lingbot-map ;;
    stage1) download_one lingbot-map-stage1 ;;
    all)
      download_one lingbot-map-long
      download_one lingbot-map
      download_one lingbot-map-stage1
      ;;
    *) echo "Unknown model key: $DOWNLOAD_MODEL" >&2; exit 1 ;;
  esac
fi

# Env file for serve / systemd
ENV_FILE="$PREFIX/lingbot-map.env"
cat >"$ENV_FILE" <<EOF
# Generated by tools/lingbot-map/install.sh — edit as needed
LINGBOT_MAP_SRC=$SRC
LINGBOT_MAP_PREFIX=$PREFIX
LINGBOT_MAP_VENV=$VENV
LINGBOT_MAP_MODEL=$PREFIX/models/lingbot-map-long.pt
LINGBOT_MAP_PORT=8080
LINGBOT_MAP_HOST=0.0.0.0
# TITAN Xp / limited VRAM defaults
LINGBOT_MAP_EXTRA_ARGS=--use_sdpa --offload_to_cpu --num_scale_frames 2 --camera_num_iterations 1
EOF

echo
echo "Install complete."
echo "  python  $PY"
echo "  env     $ENV_FILE"
echo "  model   $PREFIX/models/ (run with --download-model long if empty)"
echo "  inputs  $PREFIX/inputs/  (drop video/frames here, then serve.sh --video_path ...)"
echo
"$PY" - <<'PY'
import torch
print(f"torch {torch.__version__}  cuda_available={torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"  device0: {torch.cuda.get_device_name(0)}")
    print(f"  capability: {torch.cuda.get_device_capability(0)}")
PY
